### ISSUE TITLE
Content-type is multi-part form after upgrade to 1.6.0

### ISSUE THREAD

**Issue by ccouturesitespect** [SoftwareBrothers/admin-bro#254]
I was using:
```
├── admin-bro@1.5.0
├── admin-bro-expressjs@0.3.0
├── admin-bro-sequelizejs@0.2.6
```
and was upgraded to 1.6.0 after an `npm audit fix`. After upgrading, POSTing forms not longer worked as expected; they were being sent with `Content-type: multipart/form-data; boundary=blah`. 

I decided to upgrade all related packages to latest:
```
├── admin-bro@1.6.0
├── admin-bro-expressjs@0.4.0
├── admin-bro-sequelizejs@0.3.0
```
After doing so I was seeing `Error: Cannot find module 'express-formidable'`. Looks like a missing dependency for `admin-bro-expressjs`, I installed it.

After doing so I can no longer use the login form to get into the application. `Error: Request aborted`. Ideally I'd like to use the AdminBro package suites without vulnerabilities I'm just a little stuck. Thanks for the help!

**Comment by wojtek-krysiak** [comment]
we added support for uploading files to AdminBro in one of the latest releases. Thus we needed to change a way of sending data to `multipart` and we swap from body-parser to express-formidable. It is a peerDependency of admin-bro-expressjs so you have to install it manually.

regarding your problem, it can be caused by other middleware you use. So: 
* can you paste the express setup so I can take a look

**Comment by ccouturesitespect** [comment]
Ah, I see. Thanks very much for pointing me on the right path!

It was `app.use(express.urlencoded());` interfering.
